import { NextRequest, NextResponse } from 'next/server';
import { connectToDatabase } from '@/lib/db/mongodb';
import { Activity } from '@/lib/models/Activity';
import { Product } from '@/lib/models/Product';
import { Course } from '@/lib/models/Course';
import { RadioTrack } from '@/lib/models/RadioTrack';
import { getSessionUser } from '@/lib/auth';
import fs from 'node:fs';
import path from 'node:path';

// 1. ALL 17 YOUTH & KIDS ACTIVITIES (From Proposal Presentation)
const youthActivities = [
  {
    titleEn: 'Birthday Lineup',
    titleAr: 'تحدي ترتيب أعياد الميلاد',
    descriptionEn: 'Fun icebreaker where children arrange themselves in chronological order of birthdays using chatty mode and silent gesture challenge.',
    descriptionAr: 'لعبة تعارف ممتعة يرتب فيها الأطفال أنفسهم حسب تواريخ الميلاد بنمطين: الحوار الشفهي والتحدي الصامت بالإشارات.',
    category: 'kids_youth',
    ageRange: '6+',
    durationMinutes: 15,
    participantsMin: 10,
    participantsMax: 40,
    pricePerDayEGP: 6000,
    benefitsEn: ['Active Listening', 'Non-verbal Communication', 'Calendar Awareness'],
    benefitsAr: ['الاستماع الفعال', 'التواصل غير اللفظي', 'الوعي بالتقويم والاندماج الاجتماعي'],
    imageUrl: '/magica-games-print.png',
    isActive: true,
  },
  {
    titleEn: 'Caterpillar Race',
    titleAr: 'سباق اليرقة الجماعي',
    descriptionEn: 'Teams form a connected line with hands on shoulders, crouch down low, and race across the finish line without breaking contact.',
    descriptionAr: 'يشكل الفريق صفاً متصلاً مع الانحناء للتحرك بإيقاع جماعي موحد والوصول لخط النهاية دون انقطاع.',
    category: 'kids_youth',
    ageRange: '6+',
    durationMinutes: 20,
    participantsMin: 4,
    participantsMax: 10,
    pricePerDayEGP: 6000,
    benefitsEn: ['Gross Motor Coordination', 'Collective Balance', 'Shared Team Rhythm'],
    benefitsAr: ['التناسق الحركي الإجمالي', 'التوازن الجماعي', 'الإيقاع الحركي المشترك'],
    imageUrl: '/magica-games-print.png',
    isActive: true,
  },
  {
    titleEn: 'Friendship Bingo',
    titleAr: 'بينجو الصداقة والتعارف',
    descriptionEn: 'A networking icebreaker where kids use custom bingo cards to discover peers with matching hobbies, favorites, and shared traits.',
    descriptionAr: 'لعبة تعارف مميزة يستخدم فيها الأطفال كروت بينجو لاكتشاف الزملاء أصحاب الهوايات والاهتمامات المشتركة.',
    category: 'kids_youth',
    ageRange: '6+',
    durationMinutes: 20,
    participantsMin: 15,
    participantsMax: 50,
    pricePerDayEGP: 6000,
    benefitsEn: ['Breaking Social Anxiety', 'Discovering Shared Hobbies', 'Social Inclusion'],
    benefitsAr: ['كسر حواجز الخجل', 'اكتشاف الهوايات المشتركة', 'الدمج الاجتماعي الإيجابي'],
    imageUrl: '/magica-games-print.png',
    isActive: true,
  },
  {
    titleEn: 'Storytime Spontaneity',
    titleAr: 'تحدي القصة الارتجالية',
    descriptionEn: 'Children sit in a circle and collaboratively build an impromptu adventure story, adding exactly four words at a time.',
    descriptionAr: 'في دائرة تفاعلية، يضيف كل طفل أربع كلمات فقط بالترتيب لبناء قصة مبتكرة وشيقة بتناغم جماعي.',
    category: 'kids_youth',
    ageRange: '6+',
    durationMinutes: 20,
    participantsMin: 5,
    participantsMax: 15,
    pricePerDayEGP: 6000,
    benefitsEn: ['Verbal Expression', 'Turn-taking Skills', 'Spontaneous Creativity'],
    benefitsAr: ['التعبير اللفظي', 'مهارات انتظار الدور', 'الإبداع التلقائي'],
    imageUrl: '/magica-games-print.png',
    isActive: true,
  },
  {
    titleEn: 'Common Denominator & Team Mascot',
    titleAr: 'العامل المشترك وتصميم شعار الفريق',
    descriptionEn: 'Small groups find unique shared interests and collaboratively draw a team flag and mascot representing their collective identity.',
    descriptionAr: 'تكتشف المجموعات الصفات المشتركة بينهم ثم يتعاونون في رسم راية ومجسم يعبر عن هوية فريقهم.',
    category: 'kids_youth',
    ageRange: '6+',
    durationMinutes: 20,
    participantsMin: 4,
    participantsMax: 8,
    pricePerDayEGP: 6000,
    benefitsEn: ['Empathy & Shared Identity', 'Artistic Collaboration', 'Team Pride'],
    benefitsAr: ['التعاطف وبناء الهوية المشتركة', 'التعاون الفني', 'الفخر بروح الفريق'],
    imageUrl: '/magica-games-print.png',
    isActive: true,
  },
  {
    titleEn: 'Human Knot Puzzle',
    titleAr: 'لغز العقدة البشرية',
    descriptionEn: 'Children grab hands across a circle and work together gently to untangle the giant human knot without ever letting go.',
    descriptionAr: 'يمسك الأطفال بأيدي بعضهم البعض عبر الدائرة ويتعاونون لفك العقدة البشرية دون إفلات الأيدي.',
    category: 'kids_youth',
    ageRange: '6+',
    durationMinutes: 20,
    participantsMin: 5,
    participantsMax: 12,
    pricePerDayEGP: 6000,
    benefitsEn: ['Spatial Reasoning', 'Patience & Persistence', 'Cooperative Problem-Solving'],
    benefitsAr: ['التفكير المكاني', 'الصبر والمثابرة', 'حل المشكلات التعاوني'],
    imageUrl: '/magica-games-print.png',
    isActive: true,
  },
  {
    titleEn: 'Cup Stacking Team Challenge',
    titleAr: 'تحدي رص الأكواب الهندسي',
    descriptionEn: 'Teams of 4-8 hold strings attached to a central rubber band, pulling together to expand the band and stack tall cup pyramids without hands.',
    descriptionAr: 'يتحكم الأطفال في خيوط متصلة برباط مركزي لرفع الأكواب وبناء أهرامات هندسية دون لمسها باليد.',
    category: 'kids_youth',
    ageRange: '6+',
    durationMinutes: 25,
    participantsMin: 4,
    participantsMax: 8,
    pricePerDayEGP: 6000,
    benefitsEn: ['Fine Motor Control', 'Hand-Eye Coordination', 'Collective Patience'],
    benefitsAr: ['التحكم الحركي الدقيق', 'التناسق الحركي البصري', 'الهدوء والصبر الجماعي'],
    imageUrl: '/magica-games-print.png',
    isActive: true,
  },
  {
    titleEn: 'Hula Hoop Fingers Challenge',
    titleAr: 'طوق الهيلاهوب بالأصابع والتوازن',
    descriptionEn: 'A circle of children must lower a lightweight hula hoop to the ground using only their extended index fingertips without losing contact.',
    descriptionAr: 'يجب على المجموعة خفض طوق الهيلاهوب للأرض بهدوء باستخدام أطراف السبابة فقط دون أن يفلت الطوق.',
    category: 'kids_youth',
    ageRange: '6+',
    durationMinutes: 15,
    participantsMin: 6,
    participantsMax: 8,
    pricePerDayEGP: 6000,
    benefitsEn: ['Extreme Focus & Dexterity', 'Impulse Control', 'Group Calm & Synchrony'],
    benefitsAr: ['التركيز الشديد ودقة الأصابع', 'التحكم في الاندفاع', 'الهدوء والتناغم الجماعي'],
    imageUrl: '/magica-games-print.png',
    isActive: true,
  },
  {
    titleEn: 'Marshmallow & Toothpick STEM Challenge',
    titleAr: 'تحدي المارشملو وبناء الأبراج STEM',
    descriptionEn: 'Hands-on structural engineering where teams compete to build the tallest, strongest freestanding tower using marshmallows and toothpicks.',
    descriptionAr: 'تحدي هندسي تطبيقي يتنافس فيه الأطفال لبناء أطول وأقوى برج متماسك باستخدام المارشملو وأعواد الخشب.',
    category: 'kids_youth',
    ageRange: '6+',
    durationMinutes: 30,
    participantsMin: 4,
    participantsMax: 6,
    pricePerDayEGP: 6000,
    benefitsEn: ['STEM Physics Learning', 'Trial-and-Error Problem Solving', 'Spatial Planning'],
    benefitsAr: ['مبادئ فيزياء الـ STEM', 'حل المشكلات بالتجربة والخطأ', 'التخطيط الهندسي ثلاثي الأبعاد'],
    imageUrl: '/magica-games-print.png',
    isActive: true,
  },
  {
    titleEn: 'Chuck the Chicken Relay',
    titleAr: 'سباق رمي الدجاجة المرح',
    descriptionEn: 'High-energy outdoor field game where one team huddles while sprinting for points and the fielding team passes a safe rubber chicken in relay.',
    descriptionAr: 'سباق ميداني مفعم بالطاقة والحركة، يركض فيه الفريق لإحراز النقاط بينما يمرر الفريق الآخر دجاجة مطاطية لإيقافهم.',
    category: 'kids_youth',
    ageRange: '6+',
    durationMinutes: 25,
    participantsMin: 10,
    participantsMax: 30,
    pricePerDayEGP: 6000,
    benefitsEn: ['Cardiovascular Fitness', 'Motor Agility', 'High Team Morale'],
    benefitsAr: ['اللياقة القلبية والبدنية', 'الرشاقة وسرعة الاستجابة', 'الحماس ورفع المعنويات'],
    imageUrl: '/magica-games-print.png',
    isActive: true,
  },
  {
    titleEn: 'Classic Tug-of-War',
    titleAr: 'شد الحبل والروح الرياضية',
    descriptionEn: 'The ultimate test of collective strength and sportsmanship using a soft, heavy-duty rope under strict professional coaching and safety checks.',
    descriptionAr: 'اختبار القوة الجماعية الكلاسيكي باستخدام حبل قطني متين وآمن مع إشراف تدريبي وتشجيع حماسي.',
    category: 'kids_youth',
    ageRange: '6+',
    durationMinutes: 15,
    participantsMin: 8,
    participantsMax: 20,
    pricePerDayEGP: 6000,
    benefitsEn: ['Gross Motor Strength', 'Team Solidarity', 'Positive Sportsmanship'],
    benefitsAr: ['القوة الحركية الشاملة', 'التضامن والعمل المشترك', 'الروح الرياضية والتشجيع'],
    imageUrl: '/magica-games-print.png',
    isActive: true,
  },
  {
    titleEn: 'Hula Hoop Pass Circle',
    titleAr: 'تمرير طوق الهيلاهوب الدائري',
    descriptionEn: 'Children hold hands in a giant circle and must wiggle and step to pass a hula hoop all the way around without breaking handholds.',
    descriptionAr: 'يمسك الأطفال بأيدي بعضهم في دائرة كبيرة ويمررون طوق الهيلاهوب حول الدائرة كاملة دون إفلات الأيدي.',
    category: 'kids_youth',
    ageRange: '6+',
    durationMinutes: 20,
    participantsMin: 10,
    participantsMax: 40,
    pricePerDayEGP: 6000,
    benefitsEn: ['Body Awareness & Flexibility', 'Peer Encouragement', 'Shared Laughter'],
    benefitsAr: ['المرونة والوعي الحركي', 'تشجيع الزملاء', 'المرح والبهجة الجماعية'],
    imageUrl: '/magica-games-print.png',
    isActive: true,
  },
  {
    titleEn: 'Group Synchronized Jump Rope',
    titleAr: 'قفز الحبل الجماعي المتزامن',
    descriptionEn: 'Facilitators turn an extra-long jump rope while students take turns entering in pairs or trios to jump in perfect synchronized rhythm.',
    descriptionAr: 'يدير المدربون حبلاً طويلاً بينما يقفز الطلاب في أزواج وثلاثيات بتوقيت وإيقاع حركي موحد.',
    category: 'kids_youth',
    ageRange: '6+',
    durationMinutes: 20,
    participantsMin: 6,
    participantsMax: 15,
    pricePerDayEGP: 6000,
    benefitsEn: ['Timing & Rhythm', 'Gross Motor Agility', 'Confidence Under Movement'],
    benefitsAr: ['التوقيت والإيقاع', 'الرشاقة الحركية', 'الشجاعة والثقة بالحركة'],
    imageUrl: '/magica-games-print.png',
    isActive: true,
  },
  {
    titleEn: 'Trust Navigator Obstacle Course',
    titleAr: 'مسار العقبات ودليل الثقة',
    descriptionEn: 'Soft obstacle course where one partner is blindfolded and guided safely through hurdles using only clear, descriptive verbal instructions.',
    descriptionAr: 'مسار عقبات آمن يرتدي فيه أحد الزملاء عصابة أعين بينما يوجهه شريكه بالكلمات الواضحة والتعليمات الدقيقة.',
    category: 'kids_youth',
    ageRange: '6+',
    durationMinutes: 30,
    participantsMin: 4,
    participantsMax: 10,
    pricePerDayEGP: 6000,
    benefitsEn: ['Clear Communication', 'Trust Building', 'Active Listening'],
    benefitsAr: ['وضوح التعبير والتوجيه', 'بناء الثقة المتبادلة', 'الاستماع الفعال والتركيز'],
    imageUrl: '/magica-games-print.png',
    isActive: true,
  },
  {
    titleEn: 'Strategic Scavenger Hunt',
    titleAr: 'البحث عن الكنز والاستكشاف الاستراتيجي',
    descriptionEn: 'Teams solve riddles and decode clues to find hidden items and complete interactive challenges around the venue before time runs out.',
    descriptionAr: 'تقوم الفرق بحل الألغاز وفك الشفرات للبحث عن العناصر المخفية وإنجاز التحديات الميدانية في وقت محدد.',
    category: 'kids_youth',
    ageRange: '6+',
    durationMinutes: 40,
    participantsMin: 4,
    participantsMax: 8,
    pricePerDayEGP: 6000,
    benefitsEn: ['Logic & Deduction', 'Task Delegation', 'Curiosity & Exploration'],
    benefitsAr: ['الاستنتاج والمنطق', 'توزيع المهام والقيادة', 'الفضول والاستكشاف'],
    imageUrl: '/magica-games-print.png',
    isActive: true,
  },
  {
    titleEn: 'Creative Inventors & Team Build',
    titleAr: 'فريق المخترعين وبناء النماذج',
    descriptionEn: 'Kids receive mystery kits with cardboard, tubes, and tape to engineer a bridge, rocket, or castle, then present their prototype with pride.',
    descriptionAr: 'يحصل الأطفال على أدوات متنوعة من الكرتون والأنابيب لبناء مجسمات هندسية وتقديم ابتكارهم أمام الجميع.',
    category: 'kids_youth',
    ageRange: '6+',
    durationMinutes: 35,
    participantsMin: 4,
    participantsMax: 8,
    pricePerDayEGP: 6000,
    benefitsEn: ['Creative Ingenuity', 'Resource Sharing', 'Presentation Confidence'],
    benefitsAr: ['الابتكار وإعادة التدوير', 'مشاركة الموارد', 'الثقة في العرض والتحدث'],
    imageUrl: '/magica-games-print.png',
    isActive: true,
  },
  {
    titleEn: 'Hidden Structures Lego Memory Challenge',
    titleAr: 'الهياكل المخفية وتحدي ذاكرة الليجو',
    descriptionEn: 'A leader views a hidden Lego model for 10 seconds, runs back to describe it, and teammates must replicate the exact structure in 60 seconds.',
    descriptionAr: 'يشاهد قائد الفريق نموذجاً مخفياً لـ 10 ثوانٍ ويعود لوصفه بالكلمات لفريقه لإعادة بنائه بدقة في 60 ثانية.',
    category: 'kids_youth',
    ageRange: '6+',
    durationMinutes: 25,
    participantsMin: 4,
    participantsMax: 6,
    pricePerDayEGP: 6000,
    benefitsEn: ['Visual Short-term Memory', 'Descriptive Clarity', 'Fast Execution Teamwork'],
    benefitsAr: ['الذاكرة البصرية قصيرة المدى', 'دقة الوصف اللفظي', 'سرعة التنفيذ والتنسيق'],
    imageUrl: '/magica-games-print.png',
    isActive: true,
  },
];

// 2. ALL 20 CORPORATE FLOATABLE & INFLATABLE GAMES (From Floatable Catalog)
const floatableActivities = [
  {
    titleEn: 'Bossaball Inflatable Arena',
    titleAr: 'ملعب بوسابول الهوائي التفاعلي',
    descriptionEn: 'High-energy inflatable sport combining football, volleyball, and gymnastics on specialized trampolines. Safe, thrilling, and highly spectacular for corporate events.',
    descriptionAr: 'رياضة هوائية ممتعة تجمع بين كرة القدم والطائرة والجمباز على ترامبولين هوائي آمن ومحفز للشركات.',
    category: 'corporate',
    ageRange: 'All Ages',
    durationMinutes: 30,
    participantsMin: 8,
    participantsMax: 20,
    pricePerDayEGP: 6000,
    benefitsEn: ['Athletic Coordination', 'Team Energy', 'High Spectator Fun'],
    benefitsAr: ['التناسق الرياضي', 'طاقة وحماس الفريق', 'متعة فائقة للمشاركين والمشاهدين'],
    imageUrl: '/magica-games-print.png',
    isActive: true,
  },
  {
    titleEn: 'Big Baller Obstacle Challenge',
    titleAr: 'تحدي الكرات العملاقة المتتالية',
    descriptionEn: 'Challenging and hilarious obstacle course where players leap across large inflatable spheres without slipping off. Ideal for agility, balance, and laughter.',
    descriptionAr: 'مسار عقبات مليء بالضحك والتحدي يقفز فيه المشاركون فوق كرات عملاقة لاختبار الرشاقة والتوازن.',
    category: 'corporate',
    ageRange: 'All Ages',
    durationMinutes: 20,
    participantsMin: 4,
    participantsMax: 15,
    pricePerDayEGP: 6000,
    benefitsEn: ['Core Balance', 'Physical Agility', 'Laugh-Out-Loud Fun'],
    benefitsAr: ['التوازن البدني', 'الرشاقة الحركية', 'المرح والضحك المستمر'],
    imageUrl: '/magica-games-print.png',
    isActive: true,
  },
  {
    titleEn: 'Soap Soccer Slippery Court',
    titleAr: 'ملعب كرة الصابون المائية',
    descriptionEn: 'Traditional football on a wet, soapy inflatable court. Highly interactive, breaks down corporate barriers instantly, and guarantees continuous laughter.',
    descriptionAr: 'كرة قدم ممتعة على أرضية هوائية صابونية مبللة تكسر الحواجز الرسمية وتخلق أجواء من البهجة.',
    category: 'corporate',
    ageRange: 'All Ages',
    durationMinutes: 25,
    participantsMin: 6,
    participantsMax: 16,
    pricePerDayEGP: 6000,
    benefitsEn: ['Pure Joy & Morale', 'Cooperative Teamwork', 'Breaking Corporate Barriers'],
    benefitsAr: ['روح البهجة والمرح', 'التعاون الجماعي', 'كسر الحواجز الروتينية بين الزملاء'],
    imageUrl: '/magica-games-print.png',
    isActive: true,
  },
  {
    titleEn: 'Meltdown Rotating Arm Challenge',
    titleAr: 'تحدي الأذرع الدوارة (الميلت داون)',
    descriptionEn: 'Multiplayer game where participants stand on podiums and duck or leap over rapidly rotating sweep arms to be the last one standing.',
    descriptionAr: 'لعبة جماعية يقف فيها المتسابقون على منصات لتفادي الأذرع الدوارة السريعة واختبار سرعة رد الفعل.',
    category: 'corporate',
    ageRange: 'All Ages',
    durationMinutes: 20,
    participantsMin: 6,
    participantsMax: 8,
    pricePerDayEGP: 6000,
    benefitsEn: ['Rapid Reaction Time', 'Physical Stamina', 'Friendly Rivalry'],
    benefitsAr: ['سرعة رد الفعل', 'اللياقة والتحمل', 'المنافسة الودية الحماسية'],
    imageUrl: '/magica-games-print.png',
    isActive: true,
  },
  {
    titleEn: 'Hippo Bungee Ball Grab Arena',
    titleAr: 'تحدي الهيبو الجائع والبانجي',
    descriptionEn: 'Giant interactive human-hungry-hippos arena where players harnessed to bungee cords race to collect balls from the center against high resistance.',
    descriptionAr: 'حلبة تفاعلية عملاقة يُربط فيها المتسابقون بأحزمة بانجي مطاطية للتسابق على جمع الكرات من المنتصف.',
    category: 'corporate',
    ageRange: 'All Ages',
    durationMinutes: 20,
    participantsMin: 4,
    participantsMax: 8,
    pricePerDayEGP: 6000,
    benefitsEn: ['Strategic Coordination', 'Explosive Power', 'Team Resistance Fun'],
    benefitsAr: ['التنسيق الاستراتيجي', 'القوة الانفجارية', 'الحماس والتشجيع الجماعي'],
    imageUrl: '/magica-games-print.png',
    isActive: true,
  },
  {
    titleEn: 'Giant Football Arena',
    titleAr: 'ملعب كرة القدم العملاقة',
    descriptionEn: 'Played with a comically oversized ball on a massive inflatable field, demanding intense cooperative teamwork and strategic passing.',
    descriptionAr: 'كرة قدم بكرة ضخمة على ملعب هوائي كبير تتطلب تنسيقاً جماعياً وتواصلاً مستمراً بين اللاعبين.',
    category: 'corporate',
    ageRange: 'All Ages',
    durationMinutes: 25,
    participantsMin: 8,
    participantsMax: 20,
    pricePerDayEGP: 4800,
    benefitsEn: ['Cooperative Strategy', 'Humorous Gameplay', 'Accessible to All'],
    benefitsAr: ['التكتيك الجماعي', 'أجواء كوميدية مرحة', 'مناسبة لجميع المستويات'],
    imageUrl: '/magica-games-print.png',
    isActive: true,
  },
  {
    titleEn: 'Giant Inflatable Football Darts',
    titleAr: 'سهام كرة القدم العملاقة (الفوت ديدان)',
    descriptionEn: 'Massive inflatable dartboard where players kick velcro footballs to hit targets. Blends football skill with dartboard scoring precision.',
    descriptionAr: 'لوحة دارتس هوائية ضخمة يركل فيها اللاعبون كرات مخصصة للالتصاق بالنقاط وتسجيل أعلى سكور.',
    category: 'corporate',
    ageRange: 'All Ages',
    durationMinutes: 20,
    participantsMin: 4,
    participantsMax: 20,
    pricePerDayEGP: 3600,
    benefitsEn: ['Precision & Accuracy', 'Low-Impact High-Skill', 'Inclusive Fun'],
    benefitsAr: ['دقة التصويب والتركيز', 'مناسبة لجميع الأعمار', 'حساب النقاط الاستراتيجي'],
    imageUrl: '/magica-games-print.png',
    isActive: true,
  },
  {
    titleEn: 'Giant Volleyball Match',
    titleAr: 'الكرة الطائرة العملاقة',
    descriptionEn: 'Supersized team sport with a massive inflatable ball and net, fundamentally altering game pace to make it exceptionally collaborative.',
    descriptionAr: 'كرة طائرة بكرة عملاقة وشبكة هوائية تجعل اللعبة سهلة وشاملة لكافة أفراد الفريق.',
    category: 'corporate',
    ageRange: 'All Ages',
    durationMinutes: 20,
    participantsMin: 8,
    participantsMax: 24,
    pricePerDayEGP: 3600,
    benefitsEn: ['Team Inclusion', 'Hand Coordination', 'Non-Stop Laughter'],
    benefitsAr: ['دمج جميع أفراد الفريق', 'التناسق الحركي', 'أجواء حماسية مرحة'],
    imageUrl: '/magica-games-print.png',
    isActive: true,
  },
  {
    titleEn: 'Rabbit Inflatable Team Race',
    titleAr: 'سباق الأرانب النطاطة الجماعي',
    descriptionEn: 'Comical relay race where colleagues ride together on giant inflatable rabbit bouncers requiring synchronized timing to bounce forward.',
    descriptionAr: 'سباق تتابع مرح يمتطي فيه الزملاء أرانب هوائية عملاقة تتطلب تناغماً في القفز للتقدم نحو خط النهاية.',
    category: 'corporate',
    ageRange: 'All Ages',
    durationMinutes: 20,
    participantsMin: 4,
    participantsMax: 16,
    pricePerDayEGP: 3600,
    benefitsEn: ['Synchronized Timing', 'Non-verbal Rhythm', 'High-Energy Icebreaker'],
    benefitsAr: ['التوقيت المتزامن', 'التواصل الحركي', 'كسر الروتين ورفع الطاقة'],
    imageUrl: '/magica-games-print.png',
    isActive: true,
  },
  {
    titleEn: 'Giant Running Circle Wheel',
    titleAr: 'عجلة الجري الجماعي العملاقة',
    descriptionEn: 'Players step inside a massive rotating inflatable wheel and run in sync to race competing teams. Ultimate test of group alignment.',
    descriptionAr: 'يدخل المتسابقون داخل عجلة هوائية دوارة عملاقة ويركضون بتوافق تام لتدوير العجلة للأمام.',
    category: 'corporate',
    ageRange: 'All Ages',
    durationMinutes: 20,
    participantsMin: 4,
    participantsMax: 12,
    pricePerDayEGP: 4800,
    benefitsEn: ['Group Alignment', 'Shared Momentum', 'Pacing Coordination'],
    benefitsAr: ['التوافق الجماعي', 'استثمار الزخم الحركي', 'التحكم في سرعة الإيقاع'],
    imageUrl: '/magica-games-print.png',
    isActive: true,
  },
  {
    titleEn: 'Running Float Obstacle Track',
    titleAr: 'المسار المائي العائم',
    descriptionEn: 'Thrilling floating platform obstacle course versatile for aquatic pools or dry-land event setups. Draws continuous engagement and races.',
    descriptionAr: 'مسار عقبات عائم متعدد الأغراض لحمامات السباحة أو الملاعب لاختبار التوازن والسرعة.',
    category: 'corporate',
    ageRange: 'All Ages',
    durationMinutes: 25,
    participantsMin: 4,
    participantsMax: 20,
    pricePerDayEGP: 3600,
    benefitsEn: ['Physical Balance', 'Agility Racing', 'Spectacular Centerpiece'],
    benefitsAr: ['التوازن الحركي', 'الرشاقة وسرعة الانطلاق', 'عرض ممتع ومشوق'],
    imageUrl: '/magica-games-print.png',
    isActive: true,
  },
  {
    titleEn: 'Horses Bouncing Race',
    titleAr: 'سباق الخيول الهوائية النطاطة',
    descriptionEn: 'Hilarious competitive racing game where participants mount oversized inflatable horses and bounce their way across the track.',
    descriptionAr: 'سباق تنافسي مضحك يركب فيه المشاركون خيولاً هوائية وينطلقون قفزاً نحو خط النهاية.',
    category: 'corporate',
    ageRange: 'All Ages',
    durationMinutes: 20,
    participantsMin: 4,
    participantsMax: 16,
    pricePerDayEGP: 3600,
    benefitsEn: ['Ice Breaking', 'High Group Energy', 'Photogenic Fun'],
    benefitsAr: ['كسر الجليد', 'طاقة جماعية عالية', 'لقطات وصور تذكارية لا تُنسى'],
    imageUrl: '/magica-games-print.png',
    isActive: true,
  },
  {
    titleEn: 'Shark Relay Race',
    titleAr: 'سباق أسماك القرش التفاعلي',
    descriptionEn: 'Themed interactive race using custom shark-shaped inflatable bouncers. Great for corporate family days and vibrant relays.',
    descriptionAr: 'سباق تتابع ممتع بمجسمات أسماك القرش الهوائية لإضفاء جو من الحماس والتشويق.',
    category: 'corporate',
    ageRange: 'All Ages',
    durationMinutes: 20,
    participantsMin: 4,
    participantsMax: 16,
    pricePerDayEGP: 3600,
    benefitsEn: ['Team Relays', 'Active Movement', 'Family Day Hit'],
    benefitsAr: ['سباقات التتابع', 'النشاط والحركة', 'مثالية لليوم العائلي للشركات'],
    imageUrl: '/magica-games-print.png',
    isActive: true,
  },
  {
    titleEn: 'Doda Caterpillar Crawl',
    titleAr: 'تحدي دودة اليرقة المغلقة (دودة)',
    descriptionEn: 'Enclosed caterpillar inflatable crawling obstacle course where teams must work in perfect physical sync to move the unit forward.',
    descriptionAr: 'تحدي اليرقة المغلقة حيث يتعاون الفريق بحركات منسقة لدفع الهيكل للأمام حتى خط الفوز.',
    category: 'corporate',
    ageRange: 'All Ages',
    durationMinutes: 20,
    participantsMin: 4,
    participantsMax: 10,
    pricePerDayEGP: 2400,
    benefitsEn: ['Flawless Step Sync', 'Close Communication', 'Cooperative Agility'],
    benefitsAr: ['توافق الخطوات', 'التواصل المستمر', 'المرونة التعاونية'],
    imageUrl: '/magica-games-print.png',
    isActive: true,
  },
  {
    titleEn: 'Inflatable Field Hockey Arena',
    titleAr: 'حلبة هوكي الميدان الهوائية',
    descriptionEn: 'Oversized inflatable field hockey arena providing safe, contained, fast-paced sports competitive tournament play.',
    descriptionAr: 'ملعب هوكي هوائي مغلق يوفر منافسات رياضية سريعة وآمنة للبطولات والمجموعات.',
    category: 'corporate',
    ageRange: 'All Ages',
    durationMinutes: 25,
    participantsMin: 6,
    participantsMax: 14,
    pricePerDayEGP: 3000,
    benefitsEn: ['Hand-Eye Coordination', 'Tournament Excitement', 'Fast Strategy'],
    benefitsAr: ['التناسق الحركي البصري', 'حماس البطولات السريعة', 'التكتيك والتمرير'],
    imageUrl: '/magica-games-print.png',
    isActive: true,
  },
  {
    titleEn: 'Wrecking Ball Pedestal Arena',
    titleAr: 'تحدي كرة الهدم والتوازن (الريكينج بول)',
    descriptionEn: 'Players stand on individual raised pedestals and attempt to knock opponents off balance by swinging a massive central hanging inflatable ball.',
    descriptionAr: 'يقف اللاعبون على منصات دائرية ويحاولون تفادي وتوجيه كرة هدم عملاقة للبقاء حتى النهاية.',
    category: 'corporate',
    ageRange: 'All Ages',
    durationMinutes: 20,
    participantsMin: 4,
    participantsMax: 6,
    pricePerDayEGP: 6000,
    benefitsEn: ['Core Balance', 'Timing Strategy', 'Thrilling Competition'],
    benefitsAr: ['توازن الجذع والثبات', 'توقيت الضرب والتفادي', 'إثارة ومنافسة قوية'],
    imageUrl: '/magica-games-print.png',
    isActive: true,
  },
  {
    titleEn: 'Hilarious Sumo Suit Wrestling',
    titleAr: 'مصارعة السومو الهزلية المبطنة',
    descriptionEn: 'Safe, heavily padded oversized foam sumo suits where participants push and tumble in a padded ring. Huge laugh generator.',
    descriptionAr: 'نزال مرح ببدل السومو الإسفنجية الضخمة في حلبة مبطنة تضمن الضحك والمرح للمشاركين والحضور.',
    category: 'corporate',
    ageRange: 'All Ages',
    durationMinutes: 20,
    participantsMin: 2,
    participantsMax: 10,
    pricePerDayEGP: 6000,
    benefitsEn: ['Unstoppable Laughter', 'Safe Physical Duel', 'Unforgettable Photos'],
    benefitsAr: ['مرح وضحك متواصل', 'نزال آمن وممتع', 'صور وفيديوهات استثنائية'],
    imageUrl: '/magica-games-print.png',
    isActive: true,
  },
  {
    titleEn: 'Biliardo Foot (Snookball)',
    titleAr: 'بلياردو كرة القدم (سنوك بول)',
    descriptionEn: 'Combines the mechanics of football with billiards rules on a giant inflatable table. Players kick the cue ball to pocket designated target balls.',
    descriptionAr: 'طاولة بلياردو أرضية عملاقة تُلعب بكرات القدم، تجمع بين مهارة التسديد والتفكير الاستراتيجي للبلياردو.',
    category: 'corporate',
    ageRange: 'All Ages',
    durationMinutes: 25,
    participantsMin: 2,
    participantsMax: 8,
    pricePerDayEGP: 4800,
    benefitsEn: ['Strategic Angles', 'Precision Kicking', 'Thoughtful Gameplay'],
    benefitsAr: ['حساب الزوايا الرياضية', 'دقة الركل والتمرير', 'تفكير استراتيجي هادئ'],
    imageUrl: '/magica-games-print.png',
    isActive: true,
  },
  {
    titleEn: 'Gladiator Jousting Duel',
    titleAr: 'مبارزة الجلادياتور بالعصي الهوائية',
    descriptionEn: 'Two opponents duel on raised pedestals using soft oversized inflatable jousting batons to push each other onto the soft padded floor below.',
    descriptionAr: 'مبارزة ثنائية حماسية على منصات هوائية باستخدام عصي مبطنة لإسقاط المنافس على الأرضية الآمنة.',
    category: 'corporate',
    ageRange: 'All Ages',
    durationMinutes: 15,
    participantsMin: 2,
    participantsMax: 12,
    pricePerDayEGP: 6000,
    benefitsEn: ['Balance & Reflexes', 'High Energy Duels', 'Safe Competitive Spirit'],
    benefitsAr: ['التوازن وسرعة البديهة', 'نزالات فردية حماسية', 'روح التحدي الآمنة'],
    imageUrl: '/magica-games-print.png',
    isActive: true,
  },
  {
    titleEn: 'Dual Bungee Run Sprint',
    titleAr: 'سباق البانجي الثنائي المتفجر',
    descriptionEn: 'Head-to-head sprint down dual inflatable lanes while strapped to high-tension bungee cords, placing velcro markers before being pulled back.',
    descriptionAr: 'سباق سرعة ثنائي بأحزمة بانجي مشدودة، يتسابق فيه المتنافسان لوضع العلامة في أبعد نقطة قبل الارتداد.',
    category: 'corporate',
    ageRange: 'All Ages',
    durationMinutes: 20,
    participantsMin: 2,
    participantsMax: 12,
    pricePerDayEGP: 6000,
    benefitsEn: ['Explosive Sprint Speed', 'High Tension Resistance', 'Exciting Head-to-Head'],
    benefitsAr: ['السرعة الانفجارية', 'مقاومة الجهد البدني', 'تحدي ثنائي مشوق'],
    imageUrl: '/magica-games-print.png',
    isActive: true,
  },
];

const all37Activities = [...youthActivities, ...floatableActivities];

// 3. COURSES WITH INSTRUCTORS
const defaultCourses = [
  {
    titleEn: 'Creative STEM & Structural Prototyping',
    titleAr: 'ورشة العلوم والتفكير الهندسي STEM',
    descriptionEn: 'Hands-on engineering workshop where students design load-bearing bridges, pneumatic lifts, and mechanical models.',
    descriptionAr: 'ورشة عملية يتعلم فيها الطلاب تصميم الجسور الحاملة، الرافعات الهيدروليكية، والنماذج الميكانيكية.',
    category: 'stem_robotics',
    ageGroup: '8 - 14 Years',
    durationWeeks: 4,
    sessionsCount: 8,
    priceEGP: 2400,
    instructorNameEn: 'Eng. Mohamed Moustafa',
    instructorNameAr: 'م. محمد مصطفى',
    instructorTitleEn: 'Head of STEM & Innovation',
    instructorTitleAr: 'رئيس مسار الابتكار وSTEM',
    instructorImage: '/0logo.png',
    syllabusEn: ['Bridge & Tower Structural Physics', 'Pneumatic Mechanics', 'Trial & Error Problem Solving', 'Final Capstone Project'],
    syllabusAr: ['فيزياء بناء الأبراج والجسور', 'الميكانيكا الهيدروليكية', 'حل المشكلات بالتجربة والخطأ', 'مشروع التخرج النهائي'],
    scheduleEn: 'Saturdays & Tuesdays (4:00 PM - 6:00 PM)',
    scheduleAr: 'السبت والثلاثاء (4:00 عصراً - 6:00 مساءً)',
    isActive: true,
  },
  {
    titleEn: 'Junior Leadership & Public Speaking',
    titleAr: 'برنامج إعداد القادة الصغار وفن الخطابة',
    descriptionEn: 'Interactive program empowering youth with speech structuring, active listening, body language, and debate confidence.',
    descriptionAr: 'برنامج تفاعلي يطور مهارات الخطابة، الاستماع الفعال، لغة الجسد، وإدارة الحوار والتفاوض بثقة.',
    category: 'leadership',
    ageGroup: '10 - 16 Years',
    durationWeeks: 4,
    sessionsCount: 8,
    priceEGP: 2200,
    instructorNameEn: 'Coach Laila Ahmed',
    instructorNameAr: 'كوتش ليلى أحمد',
    instructorTitleEn: 'Youth Leadership Specialist',
    instructorTitleAr: 'أخصائية القيادة والتواصل الفعال',
    instructorImage: '/0logo.png',
    syllabusEn: ['Speech Structure & Hook Design', 'Body Language & Voice Control', 'Structured Team Debates', 'Final Showcase Speech'],
    syllabusAr: ['هيكلة الحديث وجذب الجمهور', 'لغة الجسد ونبرة الصوت', 'المناظرات الجماعية المنظمة', 'عرض التخرج أمام الجمهور'],
    scheduleEn: 'Fridays & Mondays (5:00 PM - 7:00 PM)',
    scheduleAr: 'الجمعة والاثنين (5:00 مساءً - 7:00 مساءً)',
    isActive: true,
  },
  {
    titleEn: 'Outdoor Survival & Scout Skills',
    titleAr: 'دورة المهارات الكشفية والحياة البرية',
    descriptionEn: 'Field skills masterclass covering compass navigation, emergency shelter building, knot tying, and team orienteering.',
    descriptionAr: 'دورة عملية تغطي الملاحة بالبوصلة، بناء الملاجئ الطارئة، العقد الكشفية، وإدارة الفريق في الطبيعة.',
    category: 'outdoor_survival',
    ageGroup: '9 - 15 Years',
    durationWeeks: 2,
    sessionsCount: 4,
    priceEGP: 1800,
    instructorNameEn: 'Capt. Tarek Nour',
    instructorNameAr: 'كابتن طارق نور',
    instructorTitleEn: 'Field Expedition & Scout Master',
    instructorTitleAr: 'خبير المغامرات الكشفية والبيئية',
    instructorImage: '/0logo.png',
    syllabusEn: ['Topography & Map Reading', 'Advanced Knot Mechanics', 'Outdoor Safety & First Aid', 'Wilderness Challenge'],
    syllabusAr: ['قراءة الخرائط والملاحة', 'ميكانيكا العقد والربط', 'الإسعافات الأولية والسلامة', 'تحدي التوجيه في الميدان'],
    scheduleEn: 'Fridays (10:00 AM - 2:00 PM)',
    scheduleAr: 'أيام الجمعة (10:00 صباحاً - 2:00 ظهراً)',
    isActive: true,
  },
];

// 4. RADIO TRACKS
const defaultRadioTracks = [
  {
    titleEn: 'Level Up Your World',
    titleAr: 'ارتقِ بعالمك في ماجيكا',
    artistEn: 'Magica Official Anthem',
    artistAr: 'نشيد ماجيكا الرسمي',
    category: 'anthem',
    duration: '1:15',
    audioSrc: '/audio/Level Up Your World.mp3',
    isActive: true,
    order: 1,
  },
  {
    titleEn: 'Magica Dreams',
    titleAr: 'أحلام ماجيكا',
    artistEn: 'Magica Youth Choir',
    artistAr: 'كورال شباب ماجيكا',
    category: 'song',
    duration: '3:45',
    audioSrc: '/audio/Magica Dreams.mp3',
    isActive: true,
    order: 2,
  },
  {
    titleEn: 'Making Futures Bright',
    titleAr: 'نصنع مستقبلاً مشرقاً',
    artistEn: 'Magica Camp Experience',
    artistAr: 'معسكرات ماجيكا',
    category: 'anthem',
    duration: '3:30',
    audioSrc: '/audio/Magica Making Futures Bright.mp3',
    isActive: true,
    order: 3,
  },
  {
    titleEn: 'Magica Magic',
    titleAr: 'سحر ماجيكا',
    artistEn: 'Magica Beats & Rhythms',
    artistAr: 'إيقاعات ماجيكا',
    category: 'song',
    duration: '2:43',
    audioSrc: '/audio/Magica Magic.mp3',
    isActive: true,
    order: 4,
  },
  {
    titleEn: 'Ready for the Week',
    titleAr: 'جاهزون لأسبوع المغامرة',
    artistEn: 'Field Facilitators',
    artistAr: 'ميسرو الأنشطة الميدانية',
    category: 'chant',
    duration: '2:50',
    audioSrc: '/audio/Magica Ready for the Week.mp3',
    isActive: true,
    order: 5,
  },
  {
    titleEn: 'Magica Rising',
    titleAr: 'انطلاقة ماجيكا الحماسية',
    artistEn: 'Morning Hype Crew',
    artistAr: 'هتاف الصباح الحماسي',
    category: 'chant',
    duration: '0:31',
    audioSrc: '/audio/Magica Rising.mp3',
    isActive: true,
    order: 6,
  },
  {
    titleEn: 'Own the Court',
    titleAr: 'امتلك الميدان والملعب',
    artistEn: 'Sports & Team Dynamism',
    artistAr: 'فريق الأنشطة الرياضية',
    category: 'chant',
    duration: '0:31',
    audioSrc: '/audio/Own the Court.mp3',
    isActive: true,
    order: 7,
  },
];

async function handleSeed(req: NextRequest) {
  try {
    const isProduction = process.env.NODE_ENV === 'production';
    if (isProduction) {
      const session = getSessionUser();
      const adminCookie = req.cookies.get('magica_admin_session')?.value;
      const secretHeader = req.headers.get('x-admin-passcode');

      const isAuthorized =
        (session && session.role === 'admin') ||
        adminCookie === 'authenticated' ||
        secretHeader === (process.env.ADMIN_PASSCODE || 'magica2026!');

      if (!isAuthorized) {
        return NextResponse.json(
          { success: false, message: 'Unauthorized: Admin authentication required to seed database' },
          { status: 401 }
        );
      }
    }

    await connectToDatabase();

    // 1. Scan public/supplies and public/uniform on disk
    const suppliesDir = path.join(process.cwd(), 'public', 'supplies');
    const uniformDir = path.join(process.cwd(), 'public', 'uniform');

    const suppliesFiles = fs.existsSync(suppliesDir)
      ? fs.readdirSync(suppliesDir).filter((f) => /\.(png|jpe?g|webp|avif|gif)$/i.test(f))
      : [];

    const uniformFiles = fs.existsSync(uniformDir)
      ? fs.readdirSync(uniformDir).filter((f) => /\.(png|jpe?g|webp|avif|gif)$/i.test(f))
      : [];

    // Realistic price list & titles for bags
    const suppliesPriceTiers = [1250, 1100, 1400, 950, 1350, 1200, 1500, 850];
    const uniformPriceTiers = [450, 650, 550, 750, 480, 620, 800, 520];

    // Generate product for every single photo in public/supplies/
    const generatedSuppliesProducts = suppliesFiles.map((file, idx) => ({
      nameEn: `Magica Executive CEO Backpack #${idx + 1}`,
      nameAr: `حقيبة ماجيكا التنفيذية الذكية #${idx + 1}`,
      descriptionEn: 'Waterproof ergonomic school backpack with dedicated padded tablet compartment and spine support cushion.',
      descriptionAr: 'حقيبة مدرسية تنفيذية طبية مقاومة للماء مع جيب مبطن للتابلت ودعامة مريحة للظهر والعمود الفقري.',
      category: 'event_supplies',
      priceEGP: suppliesPriceTiers[idx % suppliesPriceTiers.length],
      imageUrl: `/supplies/${file}`,
      inStock: true,
      featuresEn: ['Ergonomic Spine Support', 'Water-Resistant Heavy-Duty Fabric', 'Dedicated Laptop/Tablet Sleeve'],
      featuresAr: ['دعامة طبية لحماية الظهر', 'أقمشة فائقة التحمل ومقاومة للماء', 'جيب مخصص ومبطن للتابلت'],
    }));

    // Generate product for every single photo in public/uniform/
    const generatedUniformProducts = uniformFiles.map((file, idx) => ({
      nameEn: idx === 0 ? 'Magica Official Explorer Polo & Cap Set' : `Magica Junior Founder Premium Apparel #${idx + 1}`,
      nameAr: idx === 0 ? 'طقم بولو وكاب المستكشف الرسمي' : `يونيفورم وهودي ماجيكا الفاخر #${idx + 1}`,
      descriptionEn: 'High-breathability 100% active cotton apparel designed for school leadership and camp activities.',
      descriptionAr: 'يونيفورم قطن 100% مسامي مريح مصمم للمدارس والفعاليات الميدانية.',
      category: 'uniforms',
      priceEGP: uniformPriceTiers[idx % uniformPriceTiers.length],
      imageUrl: `/uniform/${file}`,
      inStock: true,
      featuresEn: ['100% Breathable Cotton', 'Comfort Fit for All Ages', 'Official Embroidered Badge'],
      featuresAr: ['قطن 100% مريح ومسامي', 'مقاسات لكافة المراحل العمرية', 'تطريز شعار ماجيكا الفاخر'],
    }));

    // Additional essential gear products
    const additionalGearProducts = [
      {
        nameEn: 'Team Facilitation & Field Activity Kit',
        nameAr: 'حقيبة أدوات ومعدات بناء الفرق الميدانية',
        descriptionEn: 'Comprehensive facilitator kit including elastic ropes, marker cones, blindfolds, and team bands for 50 participants.',
        descriptionAr: 'حقيبة متكاملة للمدربين تشمل حبال مطاطية، أقماع تحديد، عصابات أعين، وأشرطة تمييز لـ 50 مشارك.',
        category: 'event_supplies',
        priceEGP: 2800,
        imageUrl: suppliesFiles.length > 0 ? `/supplies/${suppliesFiles[0]}` : '/magica-Supplies-print.png',
        inStock: true,
        featuresEn: ['Complete Gear for 50+ Players', 'Durable Weatherproof Bag', 'Activity Guide Included'],
        featuresAr: ['معدات متكاملة لأكثر من 50 لاعب', 'حقيبة متينة ومقاومة للعوامل الجوية', 'دليل إرشادي مطبوع للأنشطة'],
      },
      {
        nameEn: 'Insulated Stainless Steel Sports Water Bottle',
        nameAr: 'زجاجة مياه رياضية ستانلس ستيل معزولة',
        descriptionEn: 'BPA-free stainless steel double-walled water bottle (750ml) with spill-proof straw lid.',
        descriptionAr: 'زجاجة مياه ستانلس ستيل معزولة خالية من مادة BPA سعة 750 مل مع غطاء مانع للتسرب.',
        category: 'camp_gear',
        priceEGP: 320,
        imageUrl: suppliesFiles.length > 1 ? `/supplies/${suppliesFiles}` : '/magica-Supplies-print.png',
        inStock: true,
        featuresEn: ['750ml Capacity', 'Keeps Cold for 24 Hours', 'BPA-Free Eco Friendly'],
        featuresAr: ['سعة 750 مل', 'تحفظ البرودة لمدة 24 ساعة', 'صديقة للبيئة وخالية من BPA'],
      },
      {
        nameEn: 'Magica Achievement Medals & Badges (Pack of 30)',
        nameAr: 'ميداليات وشارات التميز التذكارية (30 قطعة)',
        descriptionEn: 'Pack of 30 custom gold, silver, and bronze finish achievement medals with woven lanyards.',
        descriptionAr: 'مجموعة من 30 ميدالية وشارة تميز تذكارية للمشاركين في الفعاليات والمسابقات.',
        category: 'souvenirs',
        priceEGP: 950,
        imageUrl: '/magica-Supplies-print.png',
        inStock: true,
        featuresEn: ['Pack of 30 Medals', 'Custom Engraving Available', 'Premium Ribbon Included'],
        featuresAr: ['عبوة تحتوي على 30 ميدالية', 'إمكانية الحفر المخصص', 'شريط تعليق عالي الجودة'],
      },
    ];

    // Combine all products
    const allProducts = [...generatedSuppliesProducts, ...generatedUniformProducts, ...additionalGearProducts];

    // 2. Clear and Insert all collections
    await Activity.deleteMany({});
    await Product.deleteMany({});
    await Course.deleteMany({});
    await RadioTrack.deleteMany({});

    const seededActivities = await Activity.insertMany(all37Activities);
    const seededProducts = await Product.insertMany(allProducts);
    const seededCourses = await Course.insertMany(defaultCourses);
    const seededTracks = await RadioTrack.insertMany(defaultRadioTracks);

    return NextResponse.json({
      success: true,
      message: 'Successfully seeded all 37 activities, all supplies photos, and all uniforms photos into MongoDB!',
      importedPhotos: {
        suppliesCount: suppliesFiles.length,
        suppliesFiles,
        uniformCount: uniformFiles.length,
        uniformFiles,
      },
      summary: {
        totalActivities: seededActivities.length,
        totalProducts: seededProducts.length,
        totalCourses: seededCourses.length,
        totalRadioTracks: seededTracks.length,
      },
    });
  } catch (error: any) {
    return NextResponse.json({ success: false, error: error.message }, { status: 500 });
  }
}

export async function GET(req: NextRequest) {
  return handleSeed(req);
}

export async function POST(req: NextRequest) {
  return handleSeed(req);
}